#!/usr/bin/env python
# -*- coding: utf-8 -*-

# import os
import sys
import random

# from youtube_player import YoutubePlayer
# my player, uses urwid and vlc ^^

import gdata.youtube.service
# http://gdata-python-client.googlecode.com/hg/pydocs/gdata.youtube.service.html#YouTubeVideoQuery
# https://developers.google.com/youtube/1.0/developers_guide_python

#from ytdl import ytdl
#from ytstr import ytstr
# https://bitbucket.org/rg3/youtube-dl/wiki/Home


class YoutubeClient:
	

	def __init__(self,keyword,q,order,num_results,mode=None,time=None):

		keywords = ['search', 'download', 'stream']
		if keyword in keywords: self.keyword = keyword
		else: sys.exit('invalid keyword')
		
		self.q = q
	
		ordering_key = {'rating':'rating', 'viewcount':'viewCount','relevance':'relevance','published':'published'}
		ordering = ['rating','viewcount','relevance', 'published']
		if order in ordering: self.order = ordering_key[order]
		else: sys.exit('invalid ordering')
		
		try: self.num = int(num_results)
		except Exception as e: sys.exit('invalid number %s' %e)
		
		if mode is not None:
			self.mode = mode
		else: self.mode = False

		times_key = {'today':'today','week':'this_week','month':'this_month','time':'all_time'}
		times = ['today', 'this_week', 'this_month', 'all_time']
		if time is not None and time in times: self.time = times_key[time]
		else: self.time = False

		self.client = gdata.youtube.service.YouTubeService()
		self.execute()


	def search(self,feed):

		for entry in feed.entry:
			try:
				print '\n[video] title: %s' % entry.title.text
				print '[video] url: %s' % entry.media.player.url
				print '[video] rating: %s' % entry.rating.average
				print '[video] view count: %s' % entry.statistics.view_count
				print '[video] id: %s' % entry.media.player.url.split('watch?v=').pop().split("&")[0]
			except Exception as e: 
				print('search failed:\nError: %s' % e)


	def download(self,feed):
		
		for entry in feed.entry:
			try:
				ytdl.main(entry.media.player.url)
			except Exception as e:
				print('download failed:\nError: %s' % e)


	def stream(self,feed):
		
		import subprocess
		#subprocess.Popen(["smplayer"])
		#subprocess.Popen(["umplayer"])
		urls = []
		lines = []
		lines.append('#EXTM3U\n')
		lines.append("# Playlist created by youtube_mplayer_controller\n")
		for entry in feed.entry:
			url = str(entry.media.player.url)
			urls.append(url)
			lines.append('#EXTINF:0,%s\n%s\n'%(entry.title.text,url))
			#subprocess.Popen(["smplayer", "-add-to-playlist", entry.media.player.url])

		import tempfile
		d = tempfile.mkdtemp()
		import os
		f = open(os.path.join(d,'test.m3u'), 'w+')
		lines.append(urls[0])
		f.writelines(lines)
		f.close()
		subprocess.check_call(["smplayer", f.name])
		import shutil
		shutil.rmtree(d)
		

	def execute(self):
		
		query = gdata.youtube.service.YouTubeVideoQuery()	
		if self.q.startswith('u_'):
			query.author = self.q[2:]
		else:
			query.vq = self.q
		query.format = '5'
		query.hd = True
		if self.num != -1:
			query.max_results = self.num
		query.start_index = 1
		query.racy = 'exclude'
		query.orderby = self.order
		if self.time: query.time = self.time
		feed = self.client.YouTubeQuery(query)
		if self.mode == 'shuffle': random.shuffle(feed.entry)
		elif self.mode == 'reverse': feed.entry.reverse()
		command = self.keyword
		if command == 'download': self.download(feed)
		if command == 'stream':	self.stream(feed)
		if command == 'search':	self.search(feed)


if len(sys.argv) == 7:
	YoutubeClient(sys.argv[1], sys.argv[2], sys.argv[3], sys.argv[4], sys.argv[5], sys.argv[6])
if len(sys.argv) == 6:
	if sys.argv[5] == 'shuffle': YoutubeClient(sys.argv[1], sys.argv[2], sys.argv[3], sys.argv[4], sys.argv[5], None)
	elif sys.argv[5] == 'reverse': YoutubeClient(sys.argv[1], sys.argv[2], sys.argv[3], sys.argv[4], sys.argv[5], None)
	else: YoutubeClient(sys.argv[1], sys.argv[2], sys.argv[3], sys.argv[4], None, sys.argv[5])
if len(sys.argv) == 5:
	YoutubeClient(sys.argv[1], sys.argv[2], sys.argv[3], sys.argv[4])
